# Generated by Django 5.2 on 2025-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="PIpmGDKMSXoGjP9gaTLf6FvHt4F4z2IQ",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
