# Generated by Django 5.2 on 2025-04-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent",
            old_name="pernament_address",
            new_name="permanent_address",
        ),
    ]
