# Generated by Django 5.2.1 on 2025-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student",
            "0002_alter_parent_father_email_alter_parent_father_mobile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="father_email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="parent",
            name="father_mobile",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="parent",
            name="father_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="parent",
            name="father_occupation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="parent",
            name="mother_email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="parent",
            name="mother_mobile",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="parent",
            name="mother_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="parent",
            name="mother_occupation",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_image",
            field=models.ImageField(blank=True, null=True, upload_to="student"),
        ),
    ]
