# Generated by Django 5.2.1 on 2025-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student",
            "0003_alter_parent_father_email_alter_parent_father_mobile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
